### ISSUE TITLE
Linux compatibility

### ISSUE THREAD

**Issue by BastianKubaile** [peverett/YMDK75_SP84_ISO_build_log#1]
Hey, 

first I want to thank you for this great guide. The keyboard looks very nice and I would love to make me one too. 

What makes me doubtful about this though, is that it seems difficult to use on Linux. Apparently bootmapper is windows exclusive, but it's just needed (from my understanding) to flash the pcb. So I'm wondering, if i could use a flashed keyboard on my linux machine. Have you ever used the keyboard with a Linux OS(anything that isn't windows or mac)?  Does the keyboard work plug and play on other Windows machines, that don't have bootmapper installed?

**Comment by peverett** [comment]
Hi Bastian,

As you suggested, the Bootmapper software is for windows only. In fact it doesn't even work on every Windows 10 laptop. I tried to use it from my work laptop and it just flat out didn't write to the keyboard. It turns out my USB are write locked by corporate policy. It worked just fine from my personal laptop. 

However, once setup to your wishes, the keyboard should work perfectly fine with a Linux machine. Keyboards use the USB HID API which is standard and universal.  The keyboard is, as you say, plug and play, once you've set it up how you want.
