### ISSUE TITLE
Could you share your Layout config?

### ISSUE THREAD

**Issue by meteozond** [peverett/YMDK75_SP84_ISO_build_log#4]
Hello, you've made awesome built.

[Looks like you've made your own layout configuration](https://github.com/peverett/YMDK75_SP84_ISO_build_log#keyboard-layout), could you share it?

I've just built my own sp84 with hotswaps and found that switches sit too loose in original frame holes. 
So I'm thinking of printing my own switches frame and existing config could extremely simply my work.

**Comment by meteozond** [comment]
I've finally managed to draft layout

- [left](http://www.keyboard-layout-editor.com/#/gists/c32946fa4b6e3d9fec0e4d1c67cbd649)
- [right](http://www.keyboard-layout-editor.com/#/gists/33730a57e0b35df9d58da662283ce3a9)

**Comment by peverett** [comment]
Hi, I assume you are talking about the layout that you can define in  the Bootmapper Client application?
I can't currently share my mapping (because my Keyboard is at work and I am working from home) but I didn't change the default mapping except for the ISO layout.
If I ever get back into the office, I will try and download my config and add to the repo.
